#!/bin/bash

set -e

if [[ -z "${2}" ]] ; then
	echo "usage: $0 <username> <password>" >&2
	exit 1
fi

export file="${GIT_PROJECT_ROOT}/.htpasswd"
[[ -e "${file}" ]] || touch "${file}"
htpasswd -b -B "${file}" "${1}" "${2}"

